import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useEffect, useState } from "react";
import useImageData, { Statuses } from "@/hooks/useImageData";
import SiteLayout from "@/components/SiteLayout";
import { CreateImageDB } from "@/helpers/image-repo";
import ImageGrid from "@/components/ImageGrid";
import UploadButton from "@/components/UploadButton";
import Search from "@/components/Search";
import LoadingImages from "@/components/LoadingImages";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [initLoadingStatus, setInitLoadingStatus] = useState<Statuses>("init");
  const [state, dispatch] = useImageData<CreateImageDB>();

  useEffect(() => {
    const controller = new AbortController();
    const signal = controller.signal;

    (async () => {
      setInitLoadingStatus("fetching");
      const res = await fetch("/api/imageUploader/read", {
        signal,
      });
      const data = await res.json();

      dispatch({ type: "addInitImages", payload: data.data });
      setInitLoadingStatus("fetched");
    })();

    return () => controller.abort();
  }, [dispatch]);

  const handleUpload = async (file: File) => {
    try {
      const formData = new FormData();
      formData.append("media", file);
      const response = await fetch("/api/imageUploader/upload", {
        method: "POST",
        body: formData,
      });
      const content = await response.json();
      dispatch({ type: "addNewImage", payload: content.data });
    } catch (error) {
      console.log(error);
    }
  };

  const onRemove = async (val: string) => {
    try {
      await fetch("/api/imageUploader/delete" + val, {
        method: "DELETE",
      });
      dispatch({ type: "deleteImage", payload: val });
    } catch (error) {
      console.log(error);
    }
  };

  const onSearch = async (val: string) => {
    try {
      let searchData = [];
      if (!!val) {
        const res = await fetch("/api/imageUploader/search/" + val);
        const data = await res.json();
        searchData = data.data;
      }
      dispatch({
        type: "searchImage",
        payload: { data: searchData, term: val },
      });
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Image uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteLayout
        searchNode={<Search handleChange={onSearch} />}
        fileUploadNode={<UploadButton handleUpload={handleUpload} />}
        imagesNode={
          initLoadingStatus === "fetched" ? (
            <ImageGrid
              imageData={state.imagesData}
              imagePaths={state.images}
              onRemove={onRemove}
            />
          ) : (
            <LoadingImages />
          )
        }
      />
    </>
  );
}
